name: services
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:  
  get_it: 
  injectable:
  dependency_injection:
    path: ../dependency-injection/  

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  test: ^1.16.0
