# melos_managed_dependency_overrides: data,dependency_injection,domain,network_retrofit,shared
dependency_overrides:
  data:
    path: ../../core/data
  dependency_injection:
    path: ../../dependency-injection
  domain:
    path: ../../core/domain
  network_retrofit:
    path: ../network-retrofit
  shared:
    path: ../../core/shared
